# Neural Network by Hand
## CPE 490 590
## Rahul Bhadani

Consider a sample dataset with two features, three training samples $\mathbf{x} = [ x_1^{(1)}, x_2^{(1)} ], [ x_1^{(2)}, x_2^{(2)} ], [ x_1^{(3)}, x_2^{(3)} ] = [1, 4], [5, 6], [9, 12] $ and response variable $\mathbf{y} = y^{(1)}, y^{(2)}, y^{(3)} = [-1, 0, 1]$.

We want to build a neural networl containing two hidden layer: the first hidden layer will contain 4 hidden units or neurons, the second hidden layer will contain two hidden units or neurons. The prediction will be about predicting class value out of -1, 0, and 1. We will use cross entropy loss and optimization algorithm is stochastic gradient descent with learning rate of 0.05. The activation function to be used is sigmoid function.

The following code runs trains the neural network for two epochs.

In [1]:
import numpy as np

# Sigmoid function and its derivative
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

# Cross-Entropy loss and its derivative
def cross_entropy_loss(y_actual, y_pred):
    return -np.sum(np.multiply(y_actual, np.log(y_pred)) + np.multiply((1 - y_actual), np.log(1 - y_pred)))

def cross_entropy_loss_derivative(y_actual, y_pred):
    return -(np.divide(y_actual, y_pred) - np.divide(1 - y_actual, 1 - y_pred))

# Input samples
X = np.array([[1, 4], [5, 6], [9, 12]])

# Actual output
Y = np.array([[-1], [0], [1]])

# Weights and biases initialization from previous example
weights_hidden1 = np.array([[0.2, 0.3, 0.5, 0.9], [0.4, 0.7, 0.1, 0.8]])
biases_hidden1 = np.array([0.1, 0.2, 0.3, 0.4])
weights_hidden2 = np.array([[0.6, 0.9], [0.8, 0.2], [0.7, 0.1], [0.5, 0.3]])
biases_hidden2 = np.array([0.5, 0.6])
weights_output = np.array([[0.3], [0.6]])
biases_output = np.array([0.7])

# Learning rate
eta = 0.05


# Training for 2 iterations
for iii in range(2):
    # Forward Propagation
    print("\n============================================================")
    print("\n Iteration: {}\n".format(iii))
    print("\n____________________________________________________________\n")
    print("\n Forward Propagation")
    print("\n____________________________________________________________\n")

    hidden_layer1_output = sigmoid(np.dot(X, weights_hidden1) + biases_hidden1)
    print("Output from first hidden layer:\n", hidden_layer1_output)

    hidden_layer2_output = sigmoid(np.dot(hidden_layer1_output, weights_hidden2) + biases_hidden2)
    print("Output from second hidden layer:\n", hidden_layer2_output)

    predicted_output = sigmoid(np.dot(hidden_layer2_output, weights_output) + biases_output)
    print("Output from output layer:\n", predicted_output)

    print("\n____________________________________________________________\n")

    print("\n Backward Propagation")
    print("\n____________________________________________________________\n")

    # Backward Propagation
    error = cross_entropy_loss(Y, predicted_output)
    print("Error:\n", error)

    d_predicted_output = cross_entropy_loss_derivative(Y, predicted_output) * sigmoid_derivative(predicted_output)
    print("Derivative of the error with respect to Wo:\n", d_predicted_output)

    error_hidden_layer2 = d_predicted_output.dot(weights_output.T)
    d_hidden_layer2 = error_hidden_layer2 * sigmoid_derivative(hidden_layer2_output)
    print("Derivative of the error with respect to Wh2:\n", d_hidden_layer2)

    error_hidden_layer1 = d_hidden_layer2.dot(weights_hidden2.T)
    d_hidden_layer1 = error_hidden_layer1 * sigmoid_derivative(hidden_layer1_output)
    print("Derivative of the error with respect to Wh1:\n", d_hidden_layer1)

    # Updating Weights and Biases
    weights_output -= eta * hidden_layer2_output.T.dot(d_predicted_output)
    biases_output -= eta * np.sum(d_predicted_output)

    weights_hidden2 -= eta * hidden_layer1_output.T.dot(d_hidden_layer2)
    biases_hidden2 -= eta * np.sum(d_hidden_layer2)

    weights_hidden1 -= eta * X.T.dot(d_hidden_layer1)
    biases_hidden1 -= eta * np.sum(d_hidden_layer1)

    print("Updated weights and biases after backpropagation:")
    print("Wo:\n", weights_output)
    print("Bo:\n", biases_output)
    print("Wh2:\n", weights_hidden2)
    print("Bh2:\n", biases_hidden2)
    print("Wh1:\n", weights_hidden1)
    print("Bh1:\n", biases_hidden1)




 Iteration: 0


____________________________________________________________


 Forward Propagation

____________________________________________________________

Output from first hidden layer:
 [[0.86989153 0.96442881 0.76852478 0.98901306]
 [0.97068777 0.99726804 0.96770454 0.99993872]
 [0.9987706  0.99998763 0.99752738 0.99999999]]
Output from second hidden layer:
 [[0.94406221 0.87537515]
 [0.95510906 0.88793552]
 [0.9567904  0.89077129]]
Output from output layer:
 [[0.81883046]
 [0.8204345 ]
 [0.82075924]]

____________________________________________________________


 Backward Propagation

____________________________________________________________

Error:
 5.1315064296247845
Derivative of the error with respect to Wo:
 [[ 1.81883046]
 [ 0.8204345 ]
 [-0.17924076]]
Derivative of the error with respect to Wh2:
 [[ 0.02881505  0.11905354]
 [ 0.01055302  0.04898291]
 [-0.00222308 -0.01046384]]
Derivative of the error with respect to Wh1:
 [[ 1.40838368e-02  1.60766787e-03  5.70